services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-queue-example
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - composer_cache:/var/www/vendor
      - .:/var/www
    networks:
      - laravel

  queue:
    image: laravel-queue-example
    container_name: laravel_queue
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - composer_cache:/var/www/vendor
      - .:/var/www
    networks:
      - laravel
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: php artisan queue:work --tries=3

  web:
    image: nginx:alpine
    container_name: laravel_web
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:latest
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    networks:
      - laravel

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
  composer_cache:
